name: build
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Install dependencies
        run: |
          pipenv install --deploy --dev

      - name: Move to flask folder
        run: |
          cd app

  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Run coverage
        run: |
          pipenv run pytest --cov=app

  format:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Run black formatter
        uses: rickstaa/action-black@v1.3.1